### PR TITLE
feat: add `chrono` feature

### LINKED ISSUE #165: Add some types from chrono
- [ ] [DateTime](https://docs.rs/chrono/latest/chrono/struct.DateTime.html)
- [ ] [NaiveDate](https://docs.rs/chrono/latest/chrono/struct.NaiveDate.html)
- [ ] [NaiveTime](https://docs.rs/chrono/latest/chrono/struct.NaiveTime.html)
- [ ] [NaiveDateTime](https://docs.rs/chrono/latest/chrono/struct.NaiveDateTime.html)
- [ ] [TimeDelta](https://docs.rs/chrono/latest/chrono/struct.TimeDelta.html)

I had a look and I have to say... your clarity in thinking reflects in the code base.
However, it's way over my head at the moment.
Is it right that additions will be to a new `src/array/temporal.rs`, where we'd want to convert the above to -

**Date:**
[Date32Type](https://docs.rs/arrow/latest/arrow/datatypes/struct.Date32Type.html)

**Time:**
[Time32MillisecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.Time32MillisecondType.html)
[Time32SecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.Time32SecondType.html)

**Duration:**
[DurationSecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.DurationSecondType.html)
[DurationNanosecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.DurationNanosecondType.html)
[DurationMillisecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.DurationMillisecondType.html)
[DurationMicrosecondType](https://docs.rs/arrow/latest/arrow/datatypes/struct.DurationMicrosecondType.html)

When you have time to get into this, if you can show how to implement one in each of these groups (or maybe just one overall?), I _might_ be able to understand what's needed then and help with the remaining.

### PR DESCRIPTION
**Pull request by mbrobbel**
Add logical array support for `chrono` types: `DateTime<Utc>`, `NaiveDateTime` and `NaiveTime`.

This does not include generics to control the different logical types supported by Arrow, and it also doesn't map to parquet temportal logical types yet. This needs more work (see #183). 

Part of #165.

### CODE REVIEW

**Review by dhruv9vats — APPROVED** [review]

**Comment by v1gnesh** [comment]
Hey @mbrobbel, just wondering how much more (maybe unrelated) plumbing is left to allow revisiting this :)

**Comment by mbrobbel** [comment]
> Hey @mbrobbel, just wondering how much more (maybe unrelated) plumbing is left to allow revisiting this :)

Not much, I'll try to get to this soon.

**Comment by vultix** [comment]
Thank you for the work on this. I'm also waiting for this, and would be happy to pick this up if it would help

**Comment by mbrobbel** [comment]
> Thank you for the work on this. I'm also waiting for this, and would be happy to pick this up if it would help

If you want to help, please see #165 for more `chrono` types that need `LogicalArrayType` implementations. PRs are appreciated.

**Pull request merged**
